version: '3' 
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  bservice:
    build: 
      dockerfile: Dockerfile.dev
      context: ./Books
    volumes:
      - /app/node_modules
      - ./Books:/app
    env_file:
      - .env

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    environment:
      - WDS_SOCKET_PORT=0

  nginx:
    depends_on:
      - client
      - bservice
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3090:80"

  